(global-set-key (kbd "C-c g") 'magit-status)

(setq magit-push-always-verify nil)

;; override terrible magit-diff faces
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(git-rebase-hash ((t nil)))
 '(git-rebase-description ((t nil)))
 '(git-rebase-killed-action ((t nil)))
 '(magit-bisect-good ((t nil)))
 '(magit-bisect-skip ((t nil)))
 '(magit-bisect-bad ((t nil)))
 ;'(magit-blame-heading ((t nil)))
 '(magit-blame-summary ((t nil)))
 '(magit-blame-hash ((t nil)))
 '(magit-blame-name ((t nil)))
 '(magit-blame-date ((t nil)))
 ;'(magit-diff-file-heading ((t nil)))
 '(magit-diff-file-heading-highlight ((t nil)))
 '(magit-diff-file-heading-selection ((t nil)))
 '(magit-diff-hunk-heading ((t nil)))
 '(magit-diff-hunk-heading-highlight ((t nil)))
 '(magit-diff-hunk-heading-selection ((t nil)))
 ;'(magit-diff-lines-heading ((t nil)))
 '(magit-diff-lines-boundary ((t nil)))
 ;'(magit-diff-conflict-heading ((t nil)))
 '(magit-diff-added ((t nil)))
 '(magit-diff-removed ((t nil)))
 '(magit-diff-our ((t nil)))
 '(magit-diff-base ((t nil)))
 '(magit-diff-their ((t nil)))
 '(magit-diff-context ((t nil)))
 '(magit-diff-added-highlight
   ((t (:foreground "#22aa22"))))
 '(magit-diff-removed-highlight
   ((t (:foreground "#aa2222"))))
 '(magit-diff-our-highlight ((t nil)))
 '(magit-diff-base-highlight ((t nil)))
 '(magit-diff-their-highlight ((t nil)))
 '(magit-diff-context-highlight ((t nil)))
 '(magit-diff-whitespace-warning ((t nil)))
 '(magit-diffstat-added ((t nil)))
 '(magit-diffstat-removed ((t nil)))
 '(magit-log-graph ((t nil)))
 '(magit-log-author ((t nil)))
 '(magit-log-date ((t nil)))
 '(magit-reflog-commit ((t nil)))
 '(magit-reflog-amend ((t nil)))
 '(magit-reflog-merge ((t nil)))
 '(magit-reflog-checkout ((t nil)))
 '(magit-reflog-reset ((t nil)))
 '(magit-reflog-rebase ((t nil)))
 '(magit-reflog-cherry-pick ((t nil)))
 '(magit-reflog-remote ((t nil)))
 '(magit-reflog-other ((t nil)))
 '(magit-process-ok ((t nil)))
 '(magit-process-ng ((t nil)))
 '(magit-section-highlight ((t nil)))
 ;'(magit-section-heading ((t nil)))
 '(magit-section-heading-selection ((t nil)))
 '(magit-sequence-pick ((t nil)))
 '(magit-sequence-stop ((t nil)))
 '(magit-sequence-part ((t nil)))
 '(magit-sequence-head ((t nil)))
 '(magit-sequence-drop ((t nil)))
 '(magit-sequence-done ((t nil)))
 '(magit-sequence-onto ((t nil)))
 '(magit-header-line ((t nil)))
 ;'(magit-dimmed ((t nil)))
 ;'(magit-hash ((t nil)))
 ;'(magit-tag ((t nil)))
 ;'(magit-branch-remote ((t nil)))
 ;'(magit-branch-local ((t nil)))
 ;'(magit-branch-current ((t nil)))
 ;'(magit-head ((t nil)))
 '(magit-refname ((t nil)))
 '(magit-refname-stash ((t nil)))
 '(magit-refname-wip ((t nil)))
 '(magit-signature-good ((t nil)))
 '(magit-signature-bad ((t nil)))
 '(magit-signature-untrusted ((t nil)))
 '(magit-cherry-unmatched ((t nil)))
 '(magit-cherry-equivalent ((t nil)))
 '(magit-filename ((t nil))))
